import { Category, Gender, Word } from 'src/types/word';

export const lesson00Part02Words: Word[] = [
  {
    native: 'лифт',
    key: 'lift',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.LOCATIONS],
  },
  {
    native: 'мир',
    key: 'mir',
    gender: Gender.MASCULINE,
    categories: [Category.RELATIONS],
  },
  {
    native: 'Иртыш',
    stressIndex: 3,
    key: 'Irtysh',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.RIVERS],
  },
  {
    native: 'Нил',
    key: 'Nil',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.RIVERS],
  },
  {
    native: 'вино',
    stressIndex: 3,
    key: 'vino',
    gender: Gender.NEUTER,
    categories: [Category.ALCOHOLIC_DRINKS, Category.BEVERAGES],
  },
  {
    native: 'кино',
    stressIndex: 3,
    key: 'kino',
    gender: Gender.NEUTER,
    categories: [Category.LOCATIONS, Category.ENTERTAINMENT],
  },
  {
    native: 'ритм',
    key: 'ritm',
    gender: Gender.MASCULINE,
    categories: [Category.MUSIC],
  },
  {
    native: 'диск',
    key: 'disk',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'риск',
    key: 'risk',
    gender: Gender.MASCULINE,
    categories: [Category.CONCEPTS],
  },
  {
    native: 'артист',
    stressIndex: 3,
    key: 'artist',
    gender: Gender.MASCULINE,
    categories: [Category.PROFESSION],
  },
  {
    native: 'Минск',
    key: 'Minsk',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.CITIES],
  },
  {
    native: 'три',
    key: 'tri',
    gender: Gender.MASCULINE,
    categories: [Category.NUMBERS],
  },
  {
    native: 'тик-так',
    key: 'tik-tak',
    gender: Gender.MASCULINE,
    categories: [Category.ONOMATOPOEIC_WORD, Category.TIME],
  },
  {
    native: 'лимон',
    stressIndex: 3,
    key: 'limon',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.FRUITS],
  },
  {
    native: 'спутник',
    stressIndex: 2,
    key: 'sputnik',
    gender: Gender.MASCULINE,
    categories: [Category.OUTER_SPACE],
  },
  {
    native: 'Рим',
    key: 'Rim',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.CITIES],
  },
  {
    native: 'пилот',
    stressIndex: 3,
    key: 'pilot',
    gender: Gender.MASCULINE,
    categories: [Category.PROFESSION, Category.AIR_TRAVEL],
  },
  {
    native: 'литр',
    key: 'litr',
    gender: Gender.MASCULINE,
    categories: [Category.UNITS_OF_MEASUREMENT],
  },
  { native: 'шар', key: 'shar', gender: Gender.MASCULINE, categories: [Category.OBJECTS] },
  { native: 'наш', key: 'nash', gender: Gender.MASCULINE, categories: [Category.PERSONAL_PRONOUN] },
  { native: 'ваш', key: 'vash', gender: Gender.MASCULINE, categories: [Category.PERSONAL_PRONOUN] },
  { native: 'шум', key: 'shum', gender: Gender.MASCULINE, categories: [] },
  {
    native: 'жанр',
    key: 'zhanr',
    gender: Gender.MASCULINE,
    categories: [Category.MUSIC, Category.ENTERTAINMENT],
  },
  { native: 'жир', key: 'zhir', gender: Gender.MASCULINE, categories: [Category.FOOD] },
  { native: 'жил', key: 'zhil', gender: Gender.MASCULINE, categories: [Category.EXISTENCE] },
  { native: 'шик', key: 'shik', gender: Gender.MASCULINE, categories: [] },
  {
    native: 'цирк',
    key: 'cirk',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS, Category.ENTERTAINMENT],
  },
  { native: 'цинк', key: 'cink', gender: Gender.MASCULINE, categories: [Category.METALS] },
  {
    native: 'жираф',
    stressIndex: 3,
    key: 'zhiraf',
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'ужин',
    stressIndex: 0,
    key: 'uzhin',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.DAILY_ROUTINE],
  },
  { native: 'мой', key: 'moj', gender: Gender.MASCULINE, categories: [Category.PERSONAL_PRONOUN] },
  {
    native: 'твой',
    key: 'tvoj',
    gender: Gender.MASCULINE,
    categories: [Category.PERSONAL_PRONOUN],
  },
  { native: 'дай', key: 'daj', gender: Gender.MASCULINE, categories: [] },
  { native: 'кот', key: 'kot', gender: Gender.MASCULINE, categories: [Category.ANIMALS] },
  { native: 'код', key: 'kod', gender: Gender.MASCULINE, categories: [Category.OBJECTS] },
  { native: 'глаз', key: 'glaz', gender: Gender.MASCULINE, categories: [Category.BODY_PARTS] },
  { native: 'зуб', key: 'zub', gender: Gender.MASCULINE, categories: [Category.BODY_PARTS] },
  { native: 'нож', key: 'nozh', gender: Gender.MASCULINE, categories: [Category.CUTLERY] },
  { native: 'год', key: 'god', gender: Gender.MASCULINE, categories: [Category.TIME] },
  { native: 'муж', key: 'muzh', gender: Gender.MASCULINE, categories: [Category.FAMILY] },
  {
    native: 'арбуз',
    stressIndex: 3,
    key: 'arbuz',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.FRUITS],
  },
  {
    native: 'пирог',
    stressIndex: 3,
    key: 'pirog',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  { native: 'друг', key: 'drug', gender: Gender.MASCULINE, categories: [Category.RELATIONS] },
];
