import { Category, Gender, Word } from 'src/types/word';

export const lesson01Part01Words: Word[] = [
  {
    native: 'торт',
    key: 'tort',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.FOOD, Category.SWEETS],
  },
  {
    native: 'порт',
    key: 'port',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS],
  },
  {
    native: 'сын',
    key: 'syn',
    gender: Gender.MASCULINE,
    categories: [Category.FAMILY],
  },
  {
    native: 'ром',
    key: 'rom',
    gender: Gender.MASCULINE,
    categories: [Category.BEVERAGES],
  },
  {
    native: 'гол',
    key: 'gol',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.SPORTS],
  },
  {
    native: 'банк',
    key: 'bank',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS, Category.FINANCIAL],
  },
  {
    native: 'парк',
    key: 'park',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS],
  },
  {
    native: 'бал',
    key: 'bal',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.SPORTS],
  },
  {
    native: 'бар',
    key: 'bar',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS],
  },
  {
    native: 'суп',
    key: 'sup',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  {
    native: 'бокс',
    key: 'boks',
    gender: Gender.MASCULINE,
    categories: [Category.SPORTS],
  },
  {
    native: 'Марс',
    key: 'mars',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.OUTER_SPACE],
  },
  {
    native: 'сок',
    key: 'sok',
    gender: Gender.MASCULINE,
    categories: [Category.BEVERAGES],
  },
  {
    native: 'стол',
    key: 'stol',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.FURNITURE],
  },
  {
    native: 'стул',
    key: 'stul',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.FURNITURE],
  },
  {
    native: 'брат',
    key: 'brat',
    gender: Gender.MASCULINE,
    categories: [Category.FAMILY],
  },
  {
    native: 'Омск',
    key: 'omsk',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.CITIES],
  },
  {
    native: 'Томск',
    key: 'tomsk',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.CITIES],
  },
  {
    native: 'Дон',
    key: 'don',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.RIVERS],
  },
  {
    native: 'он',
    key: 'on',
    gender: Gender.MASCULINE,
    categories: [Category.PERSONAL_PRONOUN],
  },
  {
    native: 'два',
    key: 'dva',
    gender: Gender.FEMININE,
    categories: [Category.NUMBERS],
  },
  {
    native: 'мак',
    key: 'mak',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.PLANTS],
  },
  {
    native: 'рак',
    key: 'rak',
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'фронт',
    key: 'front',
    gender: Gender.MASCULINE,
    categories: [Category.WEATHER],
  },
  {
    native: 'глобус',
    key: 'globus',
    gender: Gender.MASCULINE,
    categories: [Category.OUTER_SPACE],
  },
  {
    native: 'вот',
    key: 'vot',
    gender: Gender.MASCULINE,
    categories: [Category.DECLARATIVE_WORD],
  },
  {
    native: 'волк',
    key: 'volk',
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'зонт',
    key: 'zont',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'нос',
    key: 'nos',
    gender: Gender.MASCULINE,
    categories: [Category.BODY_PARTS],
  },
  {
    native: 'мост',
    key: 'most',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS, Category.BUILDINGS],
  },
  {
    native: 'шарф',
    key: 'sharf',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'там',
    key: 'tam',
    gender: Gender.MASCULINE,
    categories: [Category.DECLARATIVE_WORD, Category.QUESTION_WORD],
  },
  {
    native: 'мы',
    key: 'my',
    gender: Gender.MASCULINE,
    categories: [Category.PERSONAL_PRONOUN],
  },
  {
    native: 'ты',
    key: 'ty',
    gender: Gender.MASCULINE,
    categories: [Category.PERSONAL_PRONOUN, Category.INFORMAL],
  },
  {
    native: 'вы',
    key: 'vy',
    gender: Gender.MASCULINE,
    categories: [Category.PERSONAL_PRONOUN, Category.FORMAL],
  },
  {
    native: 'бы',
    key: 'by',
    gender: Gender.MASCULINE,
    categories: [Category.EXISTENCE],
  },
  {
    native: 'да',
    key: 'da',
    gender: Gender.FEMININE,
    categories: [Category.BOOLEAN],
  },
  {
    native: 'нет',
    key: 'nyet',
    gender: Gender.MASCULINE,
    categories: [Category.BOOLEAN],
  },
  {
    native: 'Марк',
    key: 'Mark',
    gender: Gender.MASCULINE,
    categories: [Category.PERSONAL_NAMES],
  },
  {
    native: 'был',
    key: 'byl',
    gender: Gender.MASCULINE,
    categories: [Category.EXISTENCE],
  },
  {
    native: 'кто',
    key: 'kto',
    gender: Gender.NEUTER,
    categories: [Category.QUESTION_WORD],
  },
  {
    native: 'ха-ха',
    stressIndex: 4,
    key: 'ha-ha',
    gender: Gender.FEMININE,
    categories: [Category.ONOMATOPOEIC_WORD],
  },
  {
    native: 'СМС',
    key: 'SMS',
    gender: Gender.MASCULINE,
    categories: [Category.ACRONYM],
  },
  {
    native: 'СССР',
    key: 'SSSR',
    gender: Gender.MASCULINE,
    categories: [Category.ACRONYM],
  },
  {
    native: 'сыр',
    key: 'syr',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.DAIRY_PRODUCTS],
  },
  {
    native: 'МГУ',
    key: 'MGU',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.DAIRY_PRODUCTS],
  },
  {
    native: 'мэр',
    key: 'mer',
    gender: Gender.MASCULINE,
    categories: [Category.GOVERNMENT_OFFICIAL],
  },
  {
    native: 'хор',
    key: 'hor',
    gender: Gender.MASCULINE,
    categories: [Category.PROFESSION],
  },
  {
    native: 'хром',
    key: 'hrom',
    gender: Gender.MASCULINE,
    categories: [Category.MATERIALS, Category.METALS],
  },
  {
    native: 'храм',
    key: 'hram',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS, Category.BUILDINGS],
  },
  {
    native: 'как',
    key: 'kak',
    gender: Gender.MASCULINE,
    categories: [Category.COMPARATIVE_WORD],
  },
  {
    native: 'лифт',
    key: 'lift',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.LOCATIONS],
  },
  {
    native: 'мир',
    key: 'mir',
    gender: Gender.MASCULINE,
    categories: [Category.RELATIONS],
  },
  {
    native: 'Иртыш',
    key: 'Irtysh',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.RIVERS],
  },
  {
    native: 'Нил',
    key: 'Nil',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.RIVERS],
  },
  {
    native: 'вино',
    key: 'vino',
    gender: Gender.NEUTER,
    categories: [Category.ALCOHOLIC_DRINKS, Category.BEVERAGES],
  },
  {
    native: 'кино',
    key: 'kino',
    gender: Gender.NEUTER,
    categories: [Category.LOCATIONS, Category.ENTERTAINMENT],
  },
  {
    native: 'ритм',
    key: 'ritm',
    gender: Gender.MASCULINE,
    categories: [Category.MUSIC],
  },
  {
    native: 'диск',
    key: 'disk',
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'риск',
    key: 'risk',
    gender: Gender.MASCULINE,
    categories: [Category.CONCEPTS],
  },
  {
    native: 'артист',
    key: 'artist',
    gender: Gender.MASCULINE,
    categories: [Category.PROFESSION],
  },
  {
    native: 'Минск',
    key: 'Minsk',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.CITIES],
  },
  {
    native: 'три',
    key: 'tri',
    gender: Gender.MASCULINE,
    categories: [Category.NUMBERS],
  },
  {
    native: 'тик-так',
    key: 'tik-tak',
    gender: Gender.MASCULINE,
    categories: [Category.ONOMATOPOEIC_WORD, Category.TIME],
  },
  {
    native: 'лимон',
    key: 'limon',
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.FRUITS],
  },
  {
    native: 'спутник',
    key: 'sputnik',
    gender: Gender.MASCULINE,
    categories: [Category.OUTER_SPACE],
  },
  {
    native: 'Рим',
    key: 'Rim',
    gender: Gender.MASCULINE,
    categories: [Category.GEOGRAPHICAL_NAMES, Category.CITIES],
  },
  {
    native: 'пилот',
    key: 'pilot',
    gender: Gender.MASCULINE,
    categories: [Category.PROFESSION, Category.AIR_TRAVEL],
  },
  {
    native: 'литр',
    key: 'litr',
    gender: Gender.MASCULINE,
    categories: [Category.UNITS_OF_MEASUREMENT],
  },
];
