import { WORD_FOUR, WORD_ONE } from 'src/config/words/numbers-1-to-10';
import { Category } from 'src/types/category';
import { Gender } from 'src/types/gender';
import { Word } from 'src/types/word';

export const lesson00Part06Words: Word[] = [
  WORD_ONE,
  WORD_FOUR,
  {
    native: 'сено',
    stressIndex: 1,
    gender: Gender.NEUTER,
    categories: [Category.PLANTS],
  },
  {
    native: 'двор',
    gender: Gender.MASCULINE,
    categories: [Category.LOCATIONS],
  },
  {
    native: 'капуста',
    stressIndex: 3,
    gender: Gender.FEMININE,
    categories: [Category.VEGETABLES],
  },
  {
    native: 'ведро',
    stressIndex: 4,
    gender: Gender.NEUTER,
    categories: [Category.OBJECTS],
  },
  {
    native: 'голубь',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'воробей',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'бык',
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'медведь',
    stressIndex: 4,
    gender: Gender.MASCULINE,
    categories: [Category.ANIMALS],
  },
  {
    native: 'коса',
    stressIndex: 3,
    gender: Gender.FEMININE,
    categories: [Category.TOOLS],
  },
  {
    native: 'печать',
    stressIndex: 3,
    gender: Gender.FEMININE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'черешня',
    stressIndex: 3,
    gender: Gender.FEMININE,
    categories: [Category.FRUITS],
  },
  {
    native: 'улица',
    stressIndex: 0,
    gender: Gender.FEMININE,
    categories: [Category.LOCATIONS],
  },
  {
    native: 'танец',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.ACTIVITIES],
  },
  {
    native: 'калач',
    stressIndex: 3,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  {
    native: 'чисто',
    stressIndex: 1,
  },
  {
    native: 'беседа',
    stressIndex: 3,
    gender: Gender.FEMININE,
    categories: [Category.COMMUNICATION],
  },
  {
    native: 'пустыня',
    stressIndex: 4,
    gender: Gender.FEMININE,
    categories: [Category.LOCATIONS],
  },
  {
    native: 'вихрь',
    gender: Gender.MASCULINE,
  },
  {
    native: 'среда',
    stressIndex: 4,
    gender: Gender.FEMININE,
    categories: [Category.WEEKDAYS],
  },
  {
    native: 'печь',
    categories: [Category.ACTIVITIES],
  },
  {
    native: 'пушка',
    stressIndex: 1,
    gender: Gender.FEMININE,
    categories: [Category.WEAPONS, Category.OBJECTS],
  },
  {
    native: 'грабли',
    stressIndex: 2,
    categories: [Category.TOOLS],
  },
  {
    native: 'сосед',
    stressIndex: 3,
    gender: Gender.MASCULINE,
    categories: [Category.RELATIONS],
  },
  {
    native: 'немец',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.NATIONALITY],
  },
  {
    native: 'шоколад',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  {
    native: 'капитан',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.PROFESSION],
  },
  {
    native: 'телефон',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS, Category.COMMUNICATION],
  },
  {
    native: 'культура',
    stressIndex: 5,
    gender: Gender.FEMININE,
    categories: [Category.CONCEPTS],
  },
  {
    native: 'бандит',
    stressIndex: 4,
    gender: Gender.MASCULINE,
    categories: [Category.ADVERSARIES],
  },
  {
    native: 'террорист',
    stressIndex: 6,
    gender: Gender.MASCULINE,
    categories: [Category.ADVERSARIES],
  },
  {
    native: 'документ',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'космос',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.OUTER_SPACE],
  },
  {
    native: 'косметика',
    stressIndex: 4,
    gender: Gender.FEMININE,
    categories: [Category.BEAUTY],
  },
  {
    native: 'костюм',
    stressIndex: 4,
    gender: Gender.MASCULINE,
    categories: [Category.CLOTHES],
  },
  {
    native: 'оперетта',
    stressIndex: 4,
    gender: Gender.FEMININE,
    categories: [Category.ENTERTAINMENT],
  },
  {
    native: 'хоккей',
    stressIndex: 4,
    gender: Gender.MASCULINE,
    categories: [Category.SPORTS],
  },
  {
    native: 'такси',
    stressIndex: 4,
    gender: Gender.MASCULINE,
    categories: [Category.TRANSPORTATION],
  },
  {
    native: 'теннис',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.SPORTS],
  },
  {
    native: 'октябрь',
    stressIndex: 3,
    gender: Gender.MASCULINE,
    categories: [Category.MONTHS],
  },
  {
    native: 'йогурт',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.DAIRY_PRODUCTS],
  },
  {
    native: 'мандарин',
    stressIndex: 6,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD, Category.FRUITS],
  },
  {
    native: 'кофе',
    stressIndex: 1,
    gender: Gender.MASCULINE,
    categories: [Category.BEVERAGES],
  },
  {
    native: 'спагетти',
    stressIndex: 4,
    gender: Gender.NEUTER,
    categories: [Category.FOOD],
  },
  {
    native: 'майонез',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  {
    native: 'кетчуп',
    stressIndex: 4,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  {
    native: 'джинсы',
    stressIndex: 2,
    categories: [Category.CLOTHES, Category.PLURAL],
  },
  {
    native: 'сигарета',
    stressIndex: 5,
    gender: Gender.FEMININE,
    categories: [Category.TOBACCO],
  },
  {
    native: 'лампа',
    stressIndex: 1,
    gender: Gender.FEMININE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'политика',
    stressIndex: 3,
    gender: Gender.FEMININE,
    categories: [Category.POLITICS],
  },
  {
    native: 'клиника',
    stressIndex: 2,
    gender: Gender.FEMININE,
    categories: [Category.HEALTH],
  },
  {
    native: 'партнёр',
    gender: Gender.MASCULINE,
    categories: [Category.RELATIONS],
  },
  {
    native: 'портрет',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.OBJECTS],
  },
  {
    native: 'салат',
    stressIndex: 3,
    gender: Gender.MASCULINE,
    categories: [Category.FOOD],
  },
  {
    native: 'дипломат',
    stressIndex: 6,
    gender: Gender.MASCULINE,
    categories: [Category.POLITICS],
  },
  {
    native: 'конгресс',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.POLITICS],
  },
  {
    native: 'бетон',
    stressIndex: 3,
    gender: Gender.MASCULINE,
    categories: [Category.MATERIALS],
  },
  {
    native: 'бензин',
    stressIndex: 5,
    gender: Gender.MASCULINE,
    categories: [Category.MATERIALS, Category.TRANSPORTATION],
  },
];
